### PR TITLE
Custom filesystem support

### PR DESCRIPTION
**Pull request by fboranek**
MR is ready to review these features:
- fixed version of Dano MR **Add FilesystemInterface_t support**
- added support for Python as well
- moved handling relative / absolute path from several places into file system implementation
- added tests

### CODE REVIEW

**Comment by burlog** [comment]
Hi,

I've some general objections to your pull request.
 * it contains plenty coding style changes that's not needed - remove them please,
 * you added one more testing framework - it's rather general objection, there is Google Test tests now and you should use it. I know that they are disabled but we wan't do things better, don't we? But on other side for Teng3 I rewrite all tests to Catch2 in BDD style. It may be nice if you rewrite test to Catch2 either but I will be satisfied if you left them in Boost Test.
 * you made Teng depended on Boost library - remove it please (use std::hash instead).

I've some other minor objections also which we can discuss after you fix all of I mentioned above.

**Comment by fboranek** [comment]
> * it contains plenty coding style changes that's not needed - remove them please,

done

> * you made Teng depended on Boost library - remove it please (use std::hash instead).
> 

Yes, I added the dependency on boost, but it just a compile dependency. `std::hash` is since C++11 and it doesn't occur to me that the project uses C++11. I enable C++14 just on tests, actually, the tests are compiled and run only if C++14 is available. If you are ok with an upgrade to C++11 a can use the standard library.

> * you added one more testing framework - it's rather general objection, there is Google Test tests now and you should use it. I know that they are disabled but we wan't do things better, don't we? But on other side for Teng3 I rewrite all tests to Catch2 in BDD style. It may be nice if you rewrite test to Catch2 either but I will be satisfied if you left them in Boost Test.

It looks very similar. It seems to me it better rewrite it in your branch. I will gladly do that. For now let's stick with boost.

**Comment by burlog** [comment]
Let's enable C++11. It should ￼be ok.

**Comment by fboranek** [comment]
Done.

**Pull request merged**
